=== Jardel-Cald/InsProject/Auswertungen/Feedback.dtd
<!ELEMENT Formular (Person, Kontakt, Feedback)>
        <!ATTLIST Formular Datum CDATA #REQUIRED>
        <!ATTLIST Formular Uhrzeit CDATA #REQUIRED>
        <!ELEMENT Person (Anrede,Vorname,Nachname, Datum, Uhrzeit,Alter)>
        <!ELEMENT Anrede (#PCDATA)>
        <!ELEMENT Vorname (#PCDATA)>
        <!ELEMENT Nachname (#PCDATA)>
        <!ELEMENT Alter (#PCDATA)>
        <!ELEMENT Datum (#PCDATA)>
        <!ELEMENT Uhrzeit (#PCDATA)>
        <!ELEMENT Kontakt (E-Mail?,Telefonnummer?,Webseite?,Kopie_erstellen,Zurückmelden)>
        <!ELEMENT E-Mail (#PCDATA)>
        <!ELEMENT Telefonnummer (#PCDATA)>
        <!ELEMENT Webseite (#PCDATA)>
        <!ELEMENT Kopie_erstellen (#PCDATA)>
        <!ELEMENT Zurückmelden (#PCDATA)>
        <!ELEMENT Feedback (Verbesserungen?,Erneut_besuchen,Aufmerksam,Inhalt_bewertung,Aussehen_bewertung)>
        <!ELEMENT Verbesserungen (#PCDATA)>
        <!ELEMENT Erneut_besuchen (#PCDATA)>
        <!ELEMENT Aufmerksam (#PCDATA)>
        <!ELEMENT Inhalt_bewertung (#PCDATA)>
        <!ELEMENT Aussehen_bewertung (#PCDATA)>

=== Jardel-Cald/InsProject/Auswertungen/Dübel1670680708.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Formular SYSTEM "Feedback.dtd">
<Formular Datum="10.12.2022" Uhrzeit="14:58">
	<Person>
		<Anrede>Herr</Anrede>
		<Vorname>Arno</Vorname>
		<Nachname>Dübel</Nachname>
		<Datum>10.12.2022</Datum>
		<Uhrzeit>14:58</Uhrzeit>
		<Alter>61</Alter>
	</Person>
	<Kontakt>
		<E-Mail>abc@gmail.com</E-Mail>
		<Telefonnummer>232652</Telefonnummer>
		<Webseite>https://www.tutorialspoint.com/xerces/xerces_dom_create_document.htm</Webseite>
		<Kopie_erstellen>ja</Kopie_erstellen>
		<Zurückmelden>nein</Zurückmelden>
	</Kontakt>
	<Feedback>
		<Erneut_besuchen>ja</Erneut_besuchen>
		<Aufmerksam>zufall</Aufmerksam>
		<Inhalt_bewertung>1</Inhalt_bewertung>
		<Aussehen_bewertung>1</Aussehen_bewertung>
	</Feedback>
</Formular>

=== Jardel-Cald/InsProject/Auswertungen/Mustermann1670680662.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Formular SYSTEM "Feedback.dtd">
<Formular Datum="10.12.2022" Uhrzeit="14:57">
    <Person>
        <Anrede>Frau</Anrede>
        <Vorname>Erika</Vorname>
        <Nachname>Mustermann</Nachname>
        <Datum>10.12.2022</Datum>
        <Uhrzeit>14:57</Uhrzeit>
        <Alter>55</Alter>
    </Person>
    <Kontakt>
        <E-Mail>must@gmail.com</E-Mail>
        <Telefonnummer>123164512</Telefonnummer>
        <Webseite>https://www.tutorialspoint.com/xerces/xerces_dom_create_document.htm</Webseite>
        <Kopie_erstellen>nein</Kopie_erstellen>
        <Zurückmelden>nein</Zurückmelden>
    </Kontakt>
    <Feedback>
        <Verbesserungen>sehr gut</Verbesserungen>
        <Erneut_besuchen>ja</Erneut_besuchen>
        <Aufmerksam>zufall</Aufmerksam>
        <Inhalt_bewertung>2</Inhalt_bewertung>
        <Aussehen_bewertung>4</Aussehen_bewertung>
    </Feedback>
</Formular>

=== Jardel-Cald/InsProject/Auswertungen/Herrmann1670680619.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Formular SYSTEM "Feedback.dtd">
<Formular Datum="10.12.2022" Uhrzeit="14:56"><Person><Anrede>Herr</Anrede><Vorname>Paul</Vorname><Nachname>Herrmann</Nachname><Datum>10.12.2022</Datum><Uhrzeit>14:56</Uhrzeit><Alter>93</Alter></Person><Kontakt><E-Mail>herjln@t-online.de</E-Mail><Kopie_erstellen>nein</Kopie_erstellen><Zurückmelden>nein</Zurückmelden></Kontakt><Feedback><Verbesserungen>vieleicht mehr Inhalt</Verbesserungen><Erneut_besuchen>nein</Erneut_besuchen><Aufmerksam>zufall</Aufmerksam><Inhalt_bewertung>3</Inhalt_bewertung><Aussehen_bewertung>3</Aussehen_bewertung></Feedback></Formular>

=== Jardel-Cald/InsProject/Auswertungen/Müller1670680562.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Formular SYSTEM "Feedback.dtd">

<Formular Datum="10.12.2022" Uhrzeit="14:56"><Person><Anrede>Herr</Anrede><Vorname>Peter</Vorname><Nachname>Müller</Nachname><Datum>10.12.2022</Datum><Uhrzeit>14:56</Uhrzeit><Alter>42</Alter></Person><Kontakt><E-Mail>peter.Mueller@gmail.com</E-Mail><Kopie_erstellen>nein</Kopie_erstellen><Zurückmelden>nein</Zurückmelden></Kontakt><Feedback><Verbesserungen>Die Seite ist einfach komplett schlecht</Verbesserungen><Erneut_besuchen>nein</Erneut_besuchen><Aufmerksam>fernsehen</Aufmerksam><Inhalt_bewertung>6</Inhalt_bewertung><Aussehen_bewertung>5</Aussehen_bewertung></Feedback></Formular>

=== Jardel-Cald/InsProject/Auswertungen/Cramer1671705916.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Formular SYSTEM "Feedback.dtd">
<Formular Datum="22.12.2022" Uhrzeit="11:45"><Person><Anrede>Herr</Anrede><Vorname>Andreas</Vorname><Nachname>Cramer</Nachname><Datum>22.12.2022</Datum><Uhrzeit>11:45</Uhrzeit><Alter>23</Alter></Person><Kontakt><E-Mail>a@b.c</E-Mail><Kopie_erstellen>ja</Kopie_erstellen><ZurÃ¼ckmelden>nein</ZurÃ¼ckmelden></Kontakt><Feedback><Erneut_besuchen>nein</Erneut_besuchen><Aufmerksam/><Inhalt_bewertung>6</Inhalt_bewertung><Aussehen_bewertung>1</Aussehen_bewertung></Feedback></Formular>
